export { default as Seo } from './Seo'
export { default as LogoComponent } from './Logo'
export { default as NavComponent } from './Nav'
export { default as SocialNetworksComponent } from './SocialNetworks'
export { default as FrontComponent } from './Front'
export { default as FooterComponent } from './Footer'
