export { default as LayoutComponent } from './layout/Layout'
export { default as ImageComponent } from './Image'
export { default as WorksComponent } from './Works'
export { default as WhoIAmComponent } from './WhoIAm'
export { default as SkillsComponent } from './Skills'