export { default as LayoutComponent } from './layout/Layout'
export { default as ImageComponent } from './Image'
export { default as OthersProjectsComponent } from './OthersProjects'
export { default as WhoIAmComponent } from './WhoIAm'
export { default as SkillsComponent } from './Skills'
export { default as NoteworthyProjectsComponent  } from './NoteworthyProjects '